/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const CountryCodeIndexLazyImport = createFileRoute('/$countryCode/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CountryCodeIndexLazyRoute = CountryCodeIndexLazyImport.update({
  path: '/$countryCode/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$countryCode/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CountryCodeIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$countryCode/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$countryCode/": {
      "filePath": "$countryCode/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
