/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const CountryCodeIndexLazyImport = createFileRoute('/$countryCode/')()
const CountryCodeCartIndexLazyImport = createFileRoute('/$countryCode/cart/')()
const CountryCodeCategoryIndexLazyImport = createFileRoute(
  '/$countryCode/$category/',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CountryCodeIndexLazyRoute = CountryCodeIndexLazyImport.update({
  path: '/$countryCode/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$countryCode/index.lazy').then((d) => d.Route),
)

const CountryCodeCartIndexLazyRoute = CountryCodeCartIndexLazyImport.update({
  path: '/$countryCode/cart/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$countryCode/cart/index.lazy').then((d) => d.Route),
)

const CountryCodeCategoryIndexLazyRoute =
  CountryCodeCategoryIndexLazyImport.update({
    path: '/$countryCode/$category/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/$countryCode/$category/index.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$countryCode/$category/': {
      id: '/$countryCode/$category/'
      path: '/$countryCode/$category'
      fullPath: '/$countryCode/$category'
      preLoaderRoute: typeof CountryCodeCategoryIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$countryCode/cart/': {
      id: '/$countryCode/cart/'
      path: '/$countryCode/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeCartIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CountryCodeIndexLazyRoute,
  CountryCodeCategoryIndexLazyRoute,
  CountryCodeCartIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$countryCode/",
        "/$countryCode/$category/",
        "/$countryCode/cart/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$countryCode/": {
      "filePath": "$countryCode/index.lazy.tsx"
    },
    "/$countryCode/$category/": {
      "filePath": "$countryCode/$category/index.lazy.tsx"
    },
    "/$countryCode/cart/": {
      "filePath": "$countryCode/cart/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
